language: go
go: 
 - 1.8.x
 - 1.9.x
install:
 - go get -v
 - go get -v github.com/TimothyYe/skm
 - go get -v github.com/smartystreets/goconvey
 - go get -v github.com/satori/go.uuid
 - go get -v gopkg.in/urfave/cli.v1
